version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: dev.Dockerfile
    ports:
      - ${BACKEND_PORT}:8000
      - ${WEBSOCKET_PORT}:4900
    volumes:
      - ./backend:/app
      - /app/target


  frontend:
    build:
      context: invisibot-frontend
      dockerfile: dev.Dockerfile
    environment:
      NEXT_PUBLIC_BASE_URL: http://backend:8000/api
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./invisibot-frontend:/app
      - /app/node_modules
    extra_hosts:
      host.docker.internal: host-gateway
