version: "3"
services:
  frontend:
    build:
      context: invisibot-frontend
      dockerfile: dev.Dockerfile
    environment:
      BACKEND_ADDRESS: http://localhost:8000
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./invisibot-frontend:/app
      - /app/node_modules
    extra_hosts:
      host.docker.internal: host-gateway
